application: tetrahedron-sol-117
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  static_dir: index.html

- url: /css
  static_dir: css

- url: /vendor
  static_dir: vendor

- url: /js
  static_dir: js